### ISSUE TITLE
Recent change to fix rand panic, broke count

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-postgres-go#4]
The recent change to fix the rand panic created a new issue, the count is always 0 because the type the empty interface is casted to is wrong, see code snippet below:

```go
        switch r := rows[0].(type) {
        case int64: //correct type case
            count = r
        case map[string]interface{}: //wrong type cast
            count = cconv.LongConverter.ToLong(r["count"])
        }
```
https://github.com/pip-services3-go/pip-services3-postgres-go/blob/main/persistence/PostgresPersistence.go#L795

The query is correct, fixing the cast will solve the problem, alternatively you could modify the query (I think) if you wanted to maintain the map[string]interface{}.

**Comment by levichevdmitry** [comment]
Please, use new fixed version in release v1.2.7
