### ISSUE TITLE
Paging Params not working for GetPageByFilter endpoint

### ISSUE THREAD

**Issue by dthomas26** [pip-services3-go/pip-services3-postgres-go#6]
We have a table with 500+ entries. When we are trying to fetch record's via GetPageByFilter call and using following syntax we are not getting all the records. It is always showing 100 records.
```json
{
    "paging": {
        "total": true
    }
}
```
Also, this syntax is giving only the 100 records when we are requesting for more.  
```json
{
    "paging": {
        "skip": 0,
        "take": 300
    }
}
```

Expectations: when we request "total" : true we are expecting all the records to be shown.

**Comment by levichevdmitry** [comment]
Hi @dthomas26!
The "total" flag allows counting the total number of records for this filter and returns this number along with the data page.
What about "100 records only", so I think it is a limitation of max count record per page by default.
You can change it in configuration of you persistence component in "options" section
![image](https://user-images.githubusercontent.com/25570796/149380051-b11453f0-0b30-4e57-9b70-5956b421bea9.png)

**Comment by dthomas26** [comment]
@levichevdmitry  thanks for the response. Given we have different tables on different environments is there a way for us to get all the records without changing this configuration individually for every env? It is a valid use case for us to retrieve all the record's but with this config we will have to pre-configure every environment to list all the records. Once environment start's going through mutation's we will probably encounter more records. Is it something we could handle on persistence to avoid setting this config param every-time?

**Comment by levichevdmitry** [comment]
@dthomas26 , if you don't want to change configurations on your environments, you can change this parameter in "constructor" or override "Configure" method in you concrete implementation of persistence. 
For example:

```golang
type DummyPostgresPersistence struct {
	persist.IdentifiablePostgresPersistence
}

func NewDummyPostgresPersistence() *DummyPostgresPersistence {
	proto := reflect.TypeOf(tf.Dummy{})
	c := &DummyPostgresPersistence{}
	c.IdentifiablePostgresPersistence = *persist.InheritIdentifiablePostgresPersistence(c, proto, "dummies")
        c.MaxPageSize = "you value here"
	return c
}
```
or rewrite "Configure" method

```golang
func (c * DummyPostgresPersistence) Configure(config *cconf.ConfigParams) {
     c.IdentifiablePostgresPersistence.Configure(config)
     c.MaxPageSize =  "you value here"
}
```

**Comment by dthomas26** [comment]
@levichevdmitry  this is exactly what I am trying to avoid. May be setting default value to MaxPageSize should be avoided?  I was hoping setting "total" as "true" will override this value and give us back all the record's. I am not sure how can we anticipate a value to something which will change constantly? Just so we are on same page I have a table X with 1000 records on our test environment but same table has 1M record on our prod env. 
In latter case user needs to implement some kind of streaming endpoint but again that will be user/consumer choice. I hope this clarifies what I am trying to say. Setting default value to MaxPageSize probably is causing problem here?

**Comment by levichevdmitry** [comment]
@dthomas26,  If you want to take data from DB by page, you need to set max size of this page. If you want to return all records from DB without page size limitation, you can use  GetListByFilter method or make full rewrite  GetPageByFilter in you implementation of concrete persistence without limitation on max size of data page.
Sorry, but I don't see any other way for solution for your issue.

**Comment by dthomas26** [comment]
@levichevdmitry thanks for your help. I am using GetListByFilter method call for both IdentifiableMemoryPersistence and IdentifiableJsonPostgresPersistence and noticing difference in response type(when empty). 
For empty list we are getting `nil` object as response for IdentifiableMemoryPersistence while the IdentifiableJsonPostgresPersistence is giving us empty array as response. Can we pls look into this so we get same response (empty array may be) when calling from either of the persistences.

**Comment by levichevdmitry** [comment]
Hi @dthomas26!
Yes, you are right, it isn't right behavior for different types of persistence. I will review a code and try to fix it today.

**Comment by dthomas26** [comment]
Thanks @levichevdmitry ! Please let me know once we have the fix ready.

**Comment by levichevdmitry** [comment]
Hi @dthomas26 !
I updated memory persistence, you can try to use a new version https://github.com/pip-services3-go/pip-services3-data-go/releases/tag/v1.1.10
