### ISSUE TITLE
Total value for paging not populated with functional value

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-postgres-go#7]
https://github.com/pip-services3-go/pip-services3-postgres-go/blob/b1826291e3101cf4a5a07587cfa94ff54f0d4be3/persistence/PostgresPersistence.go#L678

As coded the total value will always be zero, and even though is non nil (won't panic). When paging parameters set total to true, the output is never the number of items in the page, but zero.

**Comment by levichevdmitry** [comment]
Hi, @antonio-alexander!
Main idea for "Total" value is return nil, if in request page param "Total" field is false. In other cases we always return real value of record count. 

I fixed mistake in [pip-services3-postgres-go/persistence/PostgresPersistence.go](https://github.com/pip-services3-go/pip-services3-postgres-go/blob/b1826291e3101cf4a5a07587cfa94ff54f0d4be3/persistence/PostgresPersistence.go#L678) and made new release [v1.2.8](https://github.com/pip-services3-go/pip-services3-postgres-go/releases/tag/v1.2.8).

**Comment by antonio-alexander** [comment]
Awesome, thanks!
